(in-package #:botanic)

(defun menu ()
  '((:link "/" :title "Главная")
    (:link "/about" :title "О нас")
    (:link "/about-company" :title "О компании")
    (:link "/about-clients" :title "Наши-клиенты")
    (:link "/work" :title "Этапы работы")
    (:link "/galery" :title "Галерея")
    (:link "/inter" :title "Оформление-интерьеров")
    (:link "/oforml-int" :title "Услуги по интерьеру")
    (:link "/city" :title "Городское озеленение")
    (:link "/landshaf" :title "Ландшафтный-дизайн")
    (:link "/landshafdiz" :title "Услуги по дизайну")
    (:link "/dizint-zimsad" :title "Услуги по зимнему дизайну")
    (:link "/news" :title "Выполненные проекты")
    (:link "/catalog" :title "Каталог")
    (:link "/catal" :title "Общие сведения")
    (:link "/catr" :title "Каталог растений")
    (:link "/catk" :title "Каталог кашпо")
    (:link "/iskuss" :title "Искусственные растения")
    (:link "/catalog-flower" :title "Растения")
    (:link "/catr" :title "Цветущие растения")
    (:link "/visokie" :title "Высокие")
    (:link "/dekor" :title "Декоративные")
    (:link "/prices-flower" :title "Цены")
    (:link "/rastenie-zimsad" :title "Растения для зимнего сада")
    (:link "/rastenie-offic" :title "Растения для офиса")
    (:link "/iskusstv-r" :title "Искусственные растения")
    (:link "/iskuss" :title "Общие сведения")
    (:link "/prices-iskusstv-r" :title "Цены")
    (:link "/catk" :title "Каталог кашпо")
    (:link "/catal" :title "Общие сведения")
    (:link "/prices-kashpo" :title "Цены")
    (:link "/plastic" :title "Пластик")
    (:link "/metall" :title "Металл")
    (:link "/keramika" :title "Керамика")
    (:link "/service" :title "Услуги")
    (:link "/ozelenenie" :title "Озеленение")
    (:link "/city-ozelenenie" :title "Городское озеленение")
    (:link "/landshaf-city" :title "Ландшафтные работы в городе")
    (:link "/landshaf-village" :title "Ландшафтные работы за городом")
    (:link "/fitodiz-int" :title "Интерьер")
    (:link "/fitodiz" :title "Фитодизайн")
    (:link "/kompoz-flower" :title "Композиции из цветов")
    (:link "/oforml-int" :title "Оформление интерьеров")
    (:link "/oforml-offic" :title "Оформление офиса")
    (:link "/oforml-cafe" :title "Оформление кафе")
    (:link "/flower-offic" :title "Цветы для офиса")
    (:link "/rastenie-offic" :title "Растения для офиса")
    (:link "/NY" :title "Новогоднее оформление офиса")
    (:link "/zimsad" :title "Зимний сад")
    (:link "/oforml-spa" :title "Оформление spa")
    (:link "/oforml-hotel" :title "Оформление Hotel")
    (:link "/zimsad-cottedge" :title "Оформление коттеджей")
    (:link "/articles" :title "Статьи")
    (:link "/news" :title "Новости")
    (:link "/emkosti" :title "Емкости для растений")
    (:link "/history-zimsad" :title "История зимних садов")
    (:link "/dom-offic" :title "Какие выбрать растения?")
    (:link "/spasti-offic" :title "Комнатные растения в офис")
    (:link "/akcii" :title "Акции от Botanical.LAB")
    (:link "/teory" :title "Сад в теории")
    (:link "/tehnich-har" :title "Техническое исполнение")))


;; start
(restas:start '#:botanic :port 2000)
(restas:debug-mode-on)
;; (restas:debug-mode-off)
(setf hunchentoot:*catch-errors-p* t)
